/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RestarurantPages;


import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class AddEmployee extends javax.swing.JFrame {
    
    Connection con=null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form AddEmployee
     */
    public AddEmployee() {
        initComponents();
           con = DBConnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        goBack = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_lastname = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_tel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_add = new javax.swing.JTextArea();
        date_chooser = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        r_male = new javax.swing.JRadioButton();
        r_female = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        btn_addEmp = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cmb_usertype = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_salery = new javax.swing.JTextField();
        txt_JOB = new javax.swing.JTextField();
        passLength = new javax.swing.JLabel();
        J_pass = new javax.swing.JLabel();
        J_user = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(248, 148, 6));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD EMPLOYEE");

        goBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_50px.png"))); // NOI18N
        goBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_team_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(goBack)
                .addGap(47, 47, 47)
                .addComponent(jLabel8)
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(402, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(goBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Employee ID :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Date of Birth :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, 30));

        txt_ID.setEditable(false);
        txt_ID.setBackground(new java.awt.Color(255, 255, 255));
        txt_ID.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel1.add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 190, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Firstname :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 110, 30));

        txt_firstname.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_firstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_firstnameKeyPressed(evt);
            }
        });
        jPanel1.add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 190, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Lastname :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 110, 30));

        txt_lastname.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_lastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_lastnameKeyPressed(evt);
            }
        });
        jPanel1.add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 190, 30));

        txt_email.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 190, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Gender : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Address :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, -1, 30));

        txt_tel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_telKeyPressed(evt);
            }
        });
        jPanel1.add(txt_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 190, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Contact :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, 30));

        txt_add.setColumns(20);
        txt_add.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_add.setRows(5);
        jScrollPane1.setViewportView(txt_add);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 210, -1));

        date_chooser.setBackground(new java.awt.Color(255, 255, 255));
        date_chooser.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(date_chooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 190, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Email :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, 30));

        r_male.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        r_male.setText("Male");
        r_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maleActionPerformed(evt);
            }
        });
        jPanel1.add(r_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        r_female.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        r_female.setText("Female");
        r_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_femaleActionPerformed(evt);
            }
        });
        jPanel1.add(r_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Username :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 110, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("User Type :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 110, 30));

        txt_username.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_usernameKeyReleased(evt);
            }
        });
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 190, 30));

        txt_pass.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_passKeyReleased(evt);
            }
        });
        jPanel1.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 190, 30));

        btn_addEmp.setBackground(new java.awt.Color(248, 148, 6));
        btn_addEmp.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_addEmp.setText("ADD EMPLOYEE");
        btn_addEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addEmpActionPerformed(evt);
            }
        });
        jPanel1.add(btn_addEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 150, 50));

        btnClear.setBackground(new java.awt.Color(248, 148, 6));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, 150, 50));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Password :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 110, 30));

        cmb_usertype.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cmb_usertype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Waiter", "Receptionist", "Chef" }));
        jPanel1.add(cmb_usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 190, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Salery :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Job title :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, -1));

        txt_salery.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_salery.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_saleryKeyPressed(evt);
            }
        });
        jPanel1.add(txt_salery, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 190, -1));

        txt_JOB.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_JOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_JOBKeyPressed(evt);
            }
        });
        jPanel1.add(txt_JOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 190, -1));

        passLength.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(passLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 350, 20));

        J_pass.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        J_pass.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(J_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, 30, 30));

        J_user.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        J_user.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(J_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here
        //clearing all the fileds
        txt_ID.setText("");
        txt_firstname.setText("");
        txt_lastname.setText("");
        r_male.setSelected(false);
        r_female.setSelected(false);
        date_chooser.setDate(null);
        txt_email.setText("");
        txt_tel.setText("");
        txt_add.setText("");
        txt_JOB.setText("");
        txt_salery.setText("");
        txt_username.setText("");
        txt_pass.setText("");
        cmb_usertype.setSelectedItem("Select");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btn_addEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addEmpActionPerformed
        // TODO add your handling code here:
        //ask the user is he/she want to add new employee

            int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to add new Employee ?","Employee Added",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(x==0){
                //add new employee to database
                try{

                    String q = "INSERT INTO `add_employee`(`Fristname`, `Lastname`, `Gender`, `Date  of Birth`, `Email`, `Contact`, `Address`, `Job Title`, `Salary`, `Username`, `Password`, `User Type`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
     
                     if(txt_username.getText().trim().isEmpty() && txt_pass.getText().trim().isEmpty() && cmb_usertype.getSelectedIndex()==0 ){
                    JOptionPane.showMessageDialog(null,"Employee added but  doesn't have a login account");

                    pst=con.prepareStatement(q);
                    pst.setString(1, txt_firstname.getText());
                    pst.setString(2, txt_lastname.getText());
                    pst.setString(3, gender);
                    SimpleDateFormat sdf = new SimpleDateFormat("yyy-MM-dd");
                    String birth = sdf.format(date_chooser.getDate());
                    pst.setString(4,birth);
                    pst.setString(5, txt_email.getText());
                    pst.setString(6, txt_tel.getText());
                    pst.setString(7, txt_add.getText());
                    pst.setString(8, txt_JOB.getText());
                    pst.setString(9, txt_salery.getText());
                    pst.setString(10, txt_username.getText());
                    pst.setString(11, txt_pass.getText());
                    pst.setString(12, cmb_usertype.getSelectedItem().toString());
                    pst.execute();
                }
                       else if(txt_pass.getText().length()<4){
                           passLength.setText("Password must contain at least 4 characters !");
                              J_pass.setText("*");
                       }
                       else if(txt_username.getText().trim().isEmpty()){
                           J_user.setText("*");
                           
                       }

                       else if(cmb_usertype.getSelectedIndex()==0){
                          JOptionPane.showMessageDialog(null, "You need to select a user type");
                       }

                       else{
                              pst=con.prepareStatement(q);
                    pst.setString(1, txt_firstname.getText());
                    pst.setString(2, txt_lastname.getText());
                    pst.setString(3, gender);
                    SimpleDateFormat sdf = new SimpleDateFormat("yyy-MM-dd");
                    String birth = sdf.format(date_chooser.getDate());
                    pst.setString(4,birth);
                    pst.setString(5, txt_email.getText());
                    pst.setString(6, txt_tel.getText());
                    pst.setString(7, txt_add.getText());
                    pst.setString(8, txt_JOB.getText());
                    pst.setString(9, txt_salery.getText());
                    pst.setString(10, txt_username.getText());
                    pst.setString(11, txt_pass.getText());
                    pst.setString(12, cmb_usertype.getSelectedItem().toString());
                    pst.execute();  
                    JOptionPane.showMessageDialog(null,"Employee added");
                    JOptionPane.showMessageDialog(null, "User account has been created " + 
                            " Username : " + txt_username.getText() + " Password : " + txt_pass.getText());
                       }
 
                }//end of try
            
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }//end of catch
                
            }//end of if
 
    }//GEN-LAST:event_btn_addEmpActionPerformed

    private void r_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_femaleActionPerformed
        // TODO add your handling code here:
        //if female button is seleced  than the male button disable
        gender="Female";
        r_female.setSelected(true);
        r_male.setSelected(false);
    }//GEN-LAST:event_r_femaleActionPerformed

    private void r_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_maleActionPerformed
        // TODO add your handling code here:
        //if male button is seleced  than the female button disable
        gender="Male";
        r_male.setSelected(true);
        r_female.setSelected(false);
    }//GEN-LAST:event_r_maleActionPerformed

    private void txt_telKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telKeyPressed
        // TODO add your handling code here:
        String Contact = txt_tel.getText();
 
  
        //check number from 0 to 9
        if(evt.getKeyChar()>= '0' && evt.getKeyChar()<='9' || evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
        
                txt_tel.setEditable(true);
             
            }//end of  if
            else{
                txt_tel.setEditable(false);
                 
            }//end of  else
        
    }//GEN-LAST:event_txt_telKeyPressed

    private void goBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackMouseClicked
        // TODO add your handling code here:
        //to link add employeee page with admin page
        this.toBack();
        AdminPage ap = new AdminPage();
        ap.setVisible(true);
        ap.toFront();
        this.dispose();
    }//GEN-LAST:event_goBackMouseClicked

    private void txt_saleryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_saleryKeyPressed
        // TODO add your handling code here:
          String salary = txt_salery.getText();
        int length = salary.length();
        
        if(evt.getKeyChar()>= '0' && evt.getKeyChar()<='9' || evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
              txt_salery.setEditable(true);
            }//end of  if
            else{
                txt_salery.setEditable(false);
            }//end of  else
    }//GEN-LAST:event_txt_saleryKeyPressed

    private void txt_firstnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_firstnameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)|| evt.getKeyChar()==KeyEvent.VK_SPACE ||evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE ){   
            txt_firstname.setEditable(true); 
        }
        else{
        txt_firstname.setEditable(false);
        }
    }//GEN-LAST:event_txt_firstnameKeyPressed

    private void txt_lastnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lastnameKeyPressed
        // TODO add your handling code here:
             char c = evt.getKeyChar();
        if(Character.isLetter(c)|| evt.getKeyChar()==KeyEvent.VK_SPACE ||evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE ){   
            txt_lastname.setEditable(true); 
        }
        else{
        txt_lastname.setEditable(false);
        }
    }//GEN-LAST:event_txt_lastnameKeyPressed

    private void txt_JOBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_JOBKeyPressed
        // TODO add your handling code here:
             char c = evt.getKeyChar();
        if(Character.isLetter(c)|| evt.getKeyChar()==KeyEvent.VK_SPACE ||evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE ){   
            txt_JOB.setEditable(true); 
        }
        else{
        txt_JOB.setEditable(false);
        }
    }//GEN-LAST:event_txt_JOBKeyPressed

    private void txt_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyReleased
        // TODO add your handling code here:
        passLength.setText("");
        J_pass.setText("");
    }//GEN-LAST:event_txt_passKeyReleased

    private void txt_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyReleased
        // TODO add your handling code here:
        J_user.setText("");
    }//GEN-LAST:event_txt_usernameKeyReleased
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel J_pass;
    private javax.swing.JLabel J_user;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btn_addEmp;
    private javax.swing.JComboBox<String> cmb_usertype;
    private com.toedter.calendar.JDateChooser date_chooser;
    private javax.swing.JLabel goBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel passLength;
    private javax.swing.JRadioButton r_female;
    private javax.swing.JRadioButton r_male;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_JOB;
    private javax.swing.JTextArea txt_add;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_salery;
    private javax.swing.JTextField txt_tel;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables


private String gender;

}