/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RestarurantPages;


import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class CustomerBill extends javax.swing.JFrame {
  Connection con=null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form CusotmerBill
     */
    public CustomerBill() {
        initComponents();
          con = DBConnect.connect();
          FoodCategory();
          FoodItem();
 
    }
    
    PreparedStatement pst1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmb_FC = new javax.swing.JComboBox<>();
        cmb_SF = new javax.swing.JComboBox<>();
        btn_add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_bill = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_receipt = new javax.swing.JTextArea();
        btn_printBill = new javax.swing.JButton();
        btn_showBill = new javax.swing.JButton();
        txt_TableNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_payment = new javax.swing.JTextField();
        txt_balance = new javax.swing.JTextField();
        txt_quantity = new javax.swing.JSpinner();
        txt_amount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btn_TOTAL = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        btn_Reset = new javax.swing.JButton();
        balance = new javax.swing.JLabel();
        tableNO = new javax.swing.JLabel();
        payment = new javax.swing.JLabel();
        btn_Update = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_Logout = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Food Category :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 53, -1, 31));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Select Food :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 91, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Price :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 21, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Quantity :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 53, -1, 24));

        cmb_FC.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        cmb_FC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cmb_FC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_FCItemStateChanged(evt);
            }
        });
        jPanel2.add(cmb_FC, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 54, 239, -1));

        cmb_SF.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        cmb_SF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cmb_SF.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_SFPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel2.add(cmb_SF, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 91, 242, -1));

        btn_add.setBackground(new java.awt.Color(248, 148, 6));
        btn_add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_add.setText("ADD");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel2.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, 154, 35));

        tbl_bill.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl_bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Table No.", "Food Category", "Food Name", "Quantity", "Price", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_bill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_billMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_bill);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 148, 840, 400));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Enter Table NO. :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 20, -1, 24));

        txt_price.setEditable(false);
        txt_price.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel2.add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 21, 223, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        txt_receipt.setColumns(20);
        txt_receipt.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        txt_receipt.setRows(5);
        jScrollPane2.setViewportView(txt_receipt);

        btn_printBill.setBackground(new java.awt.Color(248, 148, 6));
        btn_printBill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_printBill.setText("PRINT BILL");
        btn_printBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printBillActionPerformed(evt);
            }
        });

        btn_showBill.setBackground(new java.awt.Color(248, 148, 6));
        btn_showBill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_showBill.setText("SHOW BILL");
        btn_showBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btn_showBill, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btn_printBill, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_showBill, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_printBill, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 140, 520, 540));

        txt_TableNo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_TableNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_TableNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TableNoKeyReleased(evt);
            }
        });
        jPanel2.add(txt_TableNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 21, 239, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Amount :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 94, -1, -1));

        txt_total.setEditable(false);
        txt_total.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel2.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 26, 240, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Payment :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 62, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Balance :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 96, -1, -1));

        txt_payment.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_payment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_paymentKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_paymentKeyReleased(evt);
            }
        });
        jPanel2.add(txt_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 62, 240, -1));

        txt_balance.setEditable(false);
        txt_balance.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel2.add(txt_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 96, 242, -1));

        txt_quantity.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_quantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        txt_quantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txt_quantityStateChanged(evt);
            }
        });
        jPanel2.add(txt_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 54, 66, -1));

        txt_amount.setEditable(false);
        txt_amount.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel2.add(txt_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 94, 223, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Total :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 26, -1, -1));

        btn_TOTAL.setBackground(new java.awt.Color(248, 148, 6));
        btn_TOTAL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_TOTAL.setText("TOTAL");
        btn_TOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TOTALActionPerformed(evt);
            }
        });
        jPanel2.add(btn_TOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 79, 154, 35));

        btn_Delete.setBackground(new java.awt.Color(248, 148, 6));
        btn_Delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Delete.setText("DELETE");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 118, 44));

        btn_Reset.setBackground(new java.awt.Color(248, 148, 6));
        btn_Reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Reset.setText("RESET");
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, 118, 44));

        balance.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        balance.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 80, 20, 23));

        tableNO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tableNO.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(tableNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 15, 22, 16));

        payment.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        payment.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(1161, 47, 20, 23));

        btn_Update.setBackground(new java.awt.Color(248, 148, 6));
        btn_Update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Update.setText("UPDATE");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 118, 44));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 103, 1410, 690));

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BILLING RECEIPT");

        btn_Logout.setBackground(new java.awt.Color(248, 148, 6));
        btn_Logout.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_Logout.setText("Log Out");
        btn_Logout.setAlignmentX(0.5F);
        btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogoutActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_bill_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel12)
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 751, Short.MAX_VALUE)
                .addComponent(btn_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        //to check id Table NO is empty and get * message
       if(txt_TableNo.getText().trim().isEmpty()){
       tableNO.setText("*");
       }//end of if
       else{
           //stores the data for jTable 
       DefaultTableModel model = new DefaultTableModel();
       model = (DefaultTableModel)tbl_bill.getModel();
      
       model.addRow(new Object[]{
        
        txt_TableNo.getText(),
        cmb_FC.getSelectedItem().toString(),
        cmb_SF.getSelectedItem().toString(),
        txt_quantity.getValue().toString(),
        txt_price.getText(),
        txt_amount.getText(),
       
        });
   //get the sum of the amount column
        int sum = 0;
        for(int j = 0 ; j<tbl_bill.getRowCount(); j++){
        sum = sum + Integer.parseInt(tbl_bill.getValueAt(j, 5).toString());
        }//end of for
         txt_total.setText(Integer.toString(sum));  
   //clear the when the add button is presed
        cmb_FC.setSelectedItem("Select");
        cmb_SF.setSelectedItem("");
        txt_price.setText(""); 
        txt_amount.setText("");
        txt_payment.setText("");
        txt_balance.setText("");  
       }//end of else
    }//GEN-LAST:event_btn_addActionPerformed

    private void cmb_FCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_FCItemStateChanged
        // TODO add your handling code here:  
        try{
            //display the values form category databe to comobox
        String fc = "SELECT `Item Name` FROM `add_fooditem` WHERE `Category` ='"+cmb_FC.getSelectedItem()+"'";
        pst=con.prepareStatement(fc);
        rs=pst.executeQuery();
        cmb_SF.removeAllItems();
        while(rs.next()){
           cmb_SF.addItem(rs.getString("Item Name"));
        }//end of while
        }//end of try
        catch(Exception e){ 
        }//end of catch      
    }//GEN-LAST:event_cmb_FCItemStateChanged

    private void cmb_SFPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_SFPopupMenuWillBecomeInvisible
        // TODO add your handling code here: 
        try{
          String item = cmb_SF.getSelectedItem().toString();
        
          String p = "SELECT  * FROM `add_fooditem` WHERE `Item Name`=?";
          pst=con.prepareStatement(p);
          pst.setString(1, item);
          rs=pst.executeQuery();
          while(rs.next()){
          String price = rs.getString("Price");
          txt_price.setText(price);
          }//end of while        
        }//end of try
        catch(Exception e){  
        }//end of catch
    }//GEN-LAST:event_cmb_SFPopupMenuWillBecomeInvisible

    private void txt_quantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txt_quantityStateChanged
        // TODO add your handling code here:
        
        int qty = Integer.parseInt(txt_quantity.getValue().toString());//convert intiger to string
        int price =Integer.parseInt(txt_price.getText());
        //get the value of qty*price
        int tot = qty * price ;
        txt_amount.setText(String.valueOf(tot));//caonverting intiger to string      
    }//GEN-LAST:event_txt_quantityStateChanged

    private void btn_showBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showBillActionPerformed
        // TODO add your handling code here:   
         int x = JOptionPane.showConfirmDialog(null, "Are you sure you done with the order ?","Order saved",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(x==0){
         if(txt_payment.getText().trim().isEmpty()){
            payment.setText("*");     
    } //end of if
         else{  
       try{  
        String sql = "INSERT INTO `income`(`Table No.`, `Total`) VALUES (?,?)";
        pst=con.prepareStatement(sql);
        pst.setString(1, txt_TableNo.getText());
        pst.setString(2, txt_total.getText());
        pst.execute();
        JOptionPane.showMessageDialog(null,"Order saved");      
        }//end of try
        catch(Exception e){
        }//end of catch
             Bill();
             Balance();
         }//end of else 
        }
    }//GEN-LAST:event_btn_showBillActionPerformed

    private void txt_paymentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_paymentKeyReleased
        // TODO add your handling code here:
           balance.setText("");
           payment.setText("");
    }//GEN-LAST:event_txt_paymentKeyReleased

    private void btn_TOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TOTALActionPerformed
        // TODO add your handling code here:
        Balance();//call method
    }//GEN-LAST:event_btn_TOTALActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        // TODO add your handling code here:
        
  try{
       int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete order   ?","Order deletet",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(x==0){
      DefaultTableModel model = (DefaultTableModel)tbl_bill.getModel();
       model.removeRow(tbl_bill.getSelectedRow());
       
        int sum = 0;
        for(int j = 0 ; j<tbl_bill.getRowCount(); j++){
        sum = sum + Integer.parseInt(tbl_bill.getValueAt(j, 5).toString());
        }//end of for
         txt_total.setText(Integer.toString(sum));
         JOptionPane.showMessageDialog(null, "Order deletet");
        }//end of if
      }//end of try
        
   catch(Exception e){
      JOptionPane.showMessageDialog(null, "Select order or the table is empty");  
    }
     cmb_FC.setSelectedItem("Select");
        cmb_SF.setSelectedItem("");
        txt_price.setText(""); 
        txt_amount.setText("");
        txt_payment.setText("");
        txt_balance.setText(""); 
   
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
        // TODO add your handling code here:
        //reset the app
        CustomerBill main = new CustomerBill();
        main.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btn_ResetActionPerformed

    private void btn_printBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printBillActionPerformed
      // TODO add your handling code here:
        
        try {
            if(txt_receipt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "You need to click show bill first");
            }else{
        
          txt_receipt.print();
            }
      } catch (Exception e) {
          JOptionPane.showMessageDialog(null, e.getMessage());
      }
    }//GEN-LAST:event_btn_printBillActionPerformed

    private void btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogoutActionPerformed
        // TODO add your handling code here:
        this.toBack();
        Login log = new Login();
        log.setVisible(true);
        log.toFront();
        this.dispose();
    }//GEN-LAST:event_btn_LogoutActionPerformed

    private void txt_TableNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TableNoKeyReleased
        // TODO add your handling code here:
       tableNO.setText("");
    }//GEN-LAST:event_txt_TableNoKeyReleased

    private void txt_TableNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TableNoKeyPressed
        // TODO add your handling code here:    
         String TableNo = txt_TableNo.getText();
         int length = TableNo.length();
         if(evt.getKeyChar()>= '0' && evt.getKeyChar()<='9' || evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
          txt_TableNo.setEditable(true);
           }//end of  if
           else{
           txt_TableNo.setEditable(false); 
           }//end of else         
    }//GEN-LAST:event_txt_TableNoKeyPressed

    private void txt_paymentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_paymentKeyPressed
        // TODO add your handling code here:
             String TableNo = txt_payment.getText();
         int length = TableNo.length();
         if(evt.getKeyChar()>= '0' && evt.getKeyChar()<='9' || evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
          txt_payment.setEditable(true);
           }//end of  if
           else{
           txt_payment.setEditable(false); 
           }//end of else 
    }//GEN-LAST:event_txt_paymentKeyPressed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
      
        try{
             int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to update order   ?","Order updated",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(x==0){
            //get table model 
            DefaultTableModel model = (DefaultTableModel)tbl_bill.getModel();
            if(tbl_bill.getSelectedRowCount()==1){
            
           String table = txt_TableNo.getText();
           String category = cmb_FC.getSelectedItem().toString();
           String name = cmb_SF.getSelectedItem().toString();
           String quantity = txt_quantity.getValue().toString();
           String price = txt_price.getText();
           String amount = txt_amount.getText();
            
           
           //update value on table display
             model.setValueAt(category, tbl_bill.getSelectedRow(),1);
             model.setValueAt(name, tbl_bill.getSelectedRow(),2);
             model.setValueAt(quantity, tbl_bill.getSelectedRow(),3);
             model.setValueAt(amount, tbl_bill.getSelectedRow(),5);
             
            int sum = 0;
        for(int j = 0 ; j<tbl_bill.getRowCount(); j++){
        sum = sum + Integer.parseInt(tbl_bill.getValueAt(j, 5).toString());
        }//end of for
         txt_total.setText(Integer.toString(sum));  
          JOptionPane.showMessageDialog(null, "Order updated");
            }
        }
            }//end of try
        catch(Exception e){ 
            JOptionPane.showMessageDialog(null, e);
         }//end of catch
        cmb_FC.setSelectedItem("Select");
        cmb_SF.setSelectedItem("");
        txt_price.setText(""); 
        txt_amount.setText("");
        txt_payment.setText("");
        txt_balance.setText(""); 
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void tbl_billMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_billMouseClicked
        // TODO add your handling code here:
         try{
                //this is for selecting a row 
            int i = tbl_bill.getSelectedRow();
            TableModel model = tbl_bill.getModel();
            txt_TableNo.setText(model.getValueAt(i, 0).toString());
            cmb_FC.setSelectedItem(model.getValueAt(i, 1));
            cmb_SF.setSelectedItem(model.getValueAt(i, 2).toString());
            txt_quantity.setValue(Integer.parseInt((String)model.getValueAt(i, 3)));
            txt_price.setText(model.getValueAt(i,4).toString());
        }//end of try
            catch (Exception e) { 
        }//end of catch
        
    }//GEN-LAST:event_tbl_billMouseClicked

    public void Balance(){
    
    if(txt_payment.getText().trim().isEmpty()){
    payment.setText("*");
    }//end of if
    else{
    int total = Integer.parseInt(txt_total.getText());//convert int to string
    int pay = Integer.parseInt(txt_payment.getText());
    
    int bal = pay - total;
    txt_balance.setText(String.valueOf(bal));//convert int to string and display the vale of pay - total
    }//end of else
    }//end of method

    public void Bill(){
        
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel)tbl_bill.getModel();
        
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd/MM/yyyy");
        Tdate.format(timer.getTime());
        
        String total = txt_total.getText();
        String pay = txt_payment.getText();
        String bal = txt_balance.getText();
        String Table = txt_TableNo.getText();
        
        //Bill_table();
        txt_receipt.setText(txt_receipt.getText()+"  **********************************************\n");
        txt_receipt.setText(txt_receipt.getText()+"                 KUPON TATIMOR                   \n");
        txt_receipt.setText(txt_receipt.getText()+"\n");
        txt_receipt.setText(txt_receipt.getText()+"Table No."+Table+"\n");
         
        
        for(int i = 0 ; i < model.getRowCount(); i++){
        
        String qty = model.getValueAt(i, 3).toString();
        String price = model.getValueAt(i, 4).toString();
        String name = model.getValueAt(i, 2).toString();
        String amount = model.getValueAt(i, 5).toString();
        
        txt_receipt.setText(txt_receipt.getText()+"\n");
        txt_receipt.setText(txt_receipt.getText()+"\n");
        txt_receipt.setText(txt_receipt.getText()+ qty+ " X " +price+"\n");
        txt_receipt.setText(txt_receipt.getText()+name+"\n");
        
        }//end of for
        txt_receipt.setText(txt_receipt.getText()+"\n");
        txt_receipt.setText(txt_receipt.getText()+"\n");
        
        
        txt_receipt.setText(txt_receipt.getText()+"TOTALE LEK    :  " +total+ "\n");
        txt_receipt.setText(txt_receipt.getText()+"\n");
        
        txt_receipt.setText(txt_receipt.getText()+"Payment       :  " +pay+ "\n");
        txt_receipt.setText(txt_receipt.getText()+"\n");
             
        txt_receipt.setText(txt_receipt.getText()+"Balance       :  " +bal+ "\n");
        
        txt_receipt.setText(txt_receipt.getText()+"\n");
        txt_receipt.setText(txt_receipt.getText()+"\n"+
                "" + Tdate.format(timer.getTime()) + 
                "\t"+ tTime.format(timer.getTime()));
                txt_receipt.setText(txt_receipt.getText()+"\n");
                txt_receipt.setText(txt_receipt.getText()+"\n");
       txt_receipt.setText(txt_receipt.getText()+"  **********************************************\n");
        
    }//end of method

   private void FoodCategory(){
    try{
        String c = "Select `Food Category` FROM  `food category`";
        pst=con.prepareStatement(c);
        rs=pst.executeQuery();
        
        while(rs.next()){
        String categ = rs.getString("Food Category");
        cmb_FC.addItem(categ); 
        }//end of while  
    }//end of try
    catch(Exception e){
      }//end of catch
    }//end of method
   
   
      private void FoodItem(){
    try{
        String c = "Select `Item Name` FROM  `add_fooditem`";
        pst=con.prepareStatement(c);
        rs=pst.executeQuery();
        
        while(rs.next()){
        String categ = rs.getString("Item Name");
        cmb_SF.addItem(categ);
        }//end of while    
    }//end of try
    catch(Exception e){
    }//end of catch
    }//end of method


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balance;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Logout;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_TOTAL;
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_printBill;
    private javax.swing.JButton btn_showBill;
    private javax.swing.JComboBox<String> cmb_FC;
    private javax.swing.JComboBox<String> cmb_SF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel payment;
    private javax.swing.JLabel tableNO;
    private javax.swing.JTable tbl_bill;
    private javax.swing.JTextField txt_TableNo;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_balance;
    private javax.swing.JTextField txt_payment;
    private javax.swing.JTextField txt_price;
    private javax.swing.JSpinner txt_quantity;
    private javax.swing.JTextArea txt_receipt;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
