/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RestarurantPages;


import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

public class EmpTable extends javax.swing.JFrame {

    /**
     * Creates new form EmpTable
     */
    
    Connection con=null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    public EmpTable() {
        initComponents();
         con = DBConnect.connect();
         tableEmp();//calling the method
         tbl_emptable.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        goback = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_employeeID = new javax.swing.JTextField();
        btn_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_emptable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(248, 148, 6));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee Table");

        goback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_50px.png"))); // NOI18N
        goback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gobackMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Enter Employee ID :");

        txt_employeeID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_employeeIDKeyPressed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(248, 148, 6));
        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(goback)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_employeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(goback)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_employeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 120));

        tbl_emptable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tbl_emptable.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        tbl_emptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Firstname", "Lastname", "Gender", "Date of Birth", "Email", "Contact", "Address", "Job Title", "Salary", "Username", "Password", "User Type"
            }
        ));
        jScrollPane1.setViewportView(tbl_emptable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1480, 610));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gobackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobackMouseClicked
        // TODO add your handling code here:
        //sending you back to agmin page
        this.toBack();
        AdminPage ap = new AdminPage();
        ap.setVisible(true);
        ap.toFront();
        this.dispose();
    }//GEN-LAST:event_gobackMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
            //ask the user is he/she want to add delete employee
    
        try{
            if(txt_employeeID.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "You need to enter a Employee ID ");}
            else{ 
      int z = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this employee ?","Delete employee",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(z==0){
            //deleting employee where id is tyoe in the search field
           String s = "Delete FROM `add_employee` WHERE `Employee ID` =?";
           pst = con.prepareStatement(s);
           pst.setString(1, txt_employeeID.getText());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Employee Deleted");
           
           String d = "DELETE FROM `wage_table` WHERE ID=?";
           pst = con.prepareStatement(d);
           pst.setString(1, txt_employeeID.getText());
           pst.executeUpdate();
        }
        
        
           }
 
    
        }//end of try
        
        catch(Exception e){
        }//end of catch
 
          tableEmp(); 
              txt_employeeID.setText("");
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void txt_employeeIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_employeeIDKeyPressed
        // TODO add your handling code here:
  
         if(evt.getKeyChar()>= '0' && evt.getKeyChar()<='9' || evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
          txt_employeeID.setEditable(true);
           }//end of  if
           else{
           txt_employeeID.setEditable(false); 
           }//end of else 
    }//GEN-LAST:event_txt_employeeIDKeyPressed
//showing databse in to the jtable
     private void tableEmp(){
    try{
     String sql = " SELECT `Employee ID`, `Fristname`, `Lastname`, `Gender`, `Date  of Birth`, `Email`, `Contact`, `Address`,  `Job Title`, `Salary`, `Username`, `Password`, `User Type` FROM `add_employee`";
     pst = con.prepareStatement(sql);
     rs=pst.executeQuery();
     tbl_emptable.setModel(DbUtils.resultSetToTableModel(rs));
     }//end of try
    catch(Exception e){         
    }//end of catch 
     }//end of method
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JLabel goback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_emptable;
    private javax.swing.JTextField txt_employeeID;
    // End of variables declaration//GEN-END:variables
}
