/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package RestarurantPages;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class Expenses extends javax.swing.JFrame {
        Connection con=null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /** Creates new form Expenses */
    public Expenses() {
        initComponents();
         con = DBConnect.connect();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        goBack = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_exp = new javax.swing.JTable();
        txt_itemID = new javax.swing.JTextField();
        txt_ItemName = new javax.swing.JTextField();
        txt_Price = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_ExpTotal = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_DELETE = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        s_quantity = new javax.swing.JSpinner();
        btn_Update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel1.setText("EXPENSES");

        goBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_50px.png"))); // NOI18N
        goBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_general_ledger_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(goBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(635, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(goBack)
                    .addComponent(jLabel1))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 110));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Item ID :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Item Name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Price :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Quantity :");

        tbl_exp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Price", "Quantity", "Exp. Total"
            }
        ));
        tbl_exp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_expMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_exp);

        txt_itemID.setEditable(false);
        txt_itemID.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txt_ItemName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txt_Price.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_Price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_PriceKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Exp.Total :");

        txt_ExpTotal.setEditable(false);
        txt_ExpTotal.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        btn_clear.setBackground(new java.awt.Color(248, 148, 6));
        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_add.setBackground(new java.awt.Color(248, 148, 6));
        btn_add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_add.setText("ADD");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_DELETE.setBackground(new java.awt.Color(248, 148, 6));
        btn_DELETE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_DELETE.setText("DELETE");
        btn_DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DELETEActionPerformed(evt);
            }
        });

        btn_save.setBackground(new java.awt.Color(248, 148, 6));
        btn_save.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        s_quantity.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        s_quantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        s_quantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                s_quantityStateChanged(evt);
            }
        });

        btn_Update.setBackground(new java.awt.Color(248, 148, 6));
        btn_Update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Update.setText("UPDATE");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel3))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_ItemName, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(txt_itemID)
                            .addComponent(txt_Price)
                            .addComponent(s_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ExpTotal)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_add)
                        .addGap(40, 40, 40)
                        .addComponent(btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(btn_DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_itemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(s_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_ExpTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 990, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        //to store the value into the table 
        DefaultTableModel model = new DefaultTableModel();
        model= (DefaultTableModel)tbl_exp.getModel();
        
         model.addRow(new Object[]{
      
         txt_itemID.getText(),
         txt_ItemName.getText(),
         txt_Price.getText(),
         s_quantity.getValue().toString(),
         txt_ExpTotal.getText(),

             }); 
    }//GEN-LAST:event_btn_addActionPerformed

    private void s_quantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_s_quantityStateChanged
        // TODO add your handling code here:
        int qty = Integer.parseInt(s_quantity.getValue().toString());//convert int to string
        int price = Integer.parseInt(txt_Price.getText());
        // get the value of qty* price
        int Exptot = qty * price;
        txt_ExpTotal.setText(String.valueOf(Exptot));      
    }//GEN-LAST:event_s_quantityStateChanged

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
       //clear button 
        txt_itemID.setText("");
        txt_ItemName.setText("");
        txt_Price.setText("");
        txt_ExpTotal.setText("");      
    }//GEN-LAST:event_btn_clearActionPerformed

    private void tbl_expMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_expMouseClicked
        // TODO add your handling code here:       
        try{
            //display the values by selecting a row 
            int t = tbl_exp.getSelectedRow();
            TableModel model = tbl_exp.getModel();
            txt_itemID.setText(model.getValueAt(t, 0).toString());
            txt_ItemName.setText(model.getValueAt(t, 1).toString());
            txt_Price.setText(model.getValueAt(t, 2).toString());
            s_quantity.setValue(Integer.parseInt((String)model.getValueAt(t, 3)));
            txt_ExpTotal.setText(model.getValueAt(t, 4).toString());
        }//end of try
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());   
        }//end of catch
    }//GEN-LAST:event_tbl_expMouseClicked

    private void btn_DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DELETEActionPerformed
        // TODO add your handling code here:        
         int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this  expenses ?","Expenses deleted",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(x==0){
        try{
            // deleting a row by selecting it 
          DefaultTableModel model = (DefaultTableModel)tbl_exp.getModel();
          model.removeRow(tbl_exp.getSelectedRow());
          
          for(int j = 0 ; j<tbl_exp.getRowCount(); j++){ 
          }//end of for
        }//end of try
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "The table is empty");
        }//end of catch 
            }
    }//GEN-LAST:event_btn_DELETEActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here: 
          int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to save this expenses?","Expenses saved ",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(x==0){
        try{
         //all displayed  values will be saved  in to the databes  
        String sql = "INSERT INTO `expenses`(`Item Name`, `Price`, `Quantity`, `Exp.Total`) VALUES (?,?,?,?)";
        pst=con.prepareStatement(sql);
        pst.setString(1, txt_ItemName.getText());
        pst.setString(2, txt_Price.getText());
        pst.setString(3, s_quantity.getValue().toString());
        pst.setString(4, txt_ExpTotal.getText());
        pst.execute();
           JOptionPane.showMessageDialog(null,"Expenses Added");      
        }//end of try
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }//end of catch 
            }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void goBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackMouseClicked
        // TODO add your handling code here:
        //send you back to admin page
        this.toBack();
        AdminPage ap = new AdminPage();
        ap.setVisible(true);
        ap.toFront();
        this.dispose();
    }//GEN-LAST:event_goBackMouseClicked

    private void txt_PriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PriceKeyPressed
        // TODO add your handling code here:
                    String price = txt_Price.getText();
        int length = price.length();
        
        if(evt.getKeyChar()>= '0' && evt.getKeyChar()<='9' || evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
              txt_Price.setEditable(true);
            }//end of  if
            else{
                txt_Price.setEditable(false);
            }//end of  else
    }//GEN-LAST:event_txt_PriceKeyPressed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
         try{
            //get table model 
            DefaultTableModel model = (DefaultTableModel)tbl_exp.getModel();
            if(tbl_exp.getSelectedRowCount()==1){
            
           String ID = txt_itemID.getText();
           String name = txt_ItemName.getText();
           String price = txt_Price.getText();
           String quantity = s_quantity.getValue().toString();
           String Total = txt_ExpTotal.getText();
            
           
           //update value on table display
           model.setValueAt(ID, tbl_exp.getSelectedRow(),0);
           model.setValueAt(name, tbl_exp.getSelectedRow(),1);
           model.setValueAt(price, tbl_exp.getSelectedRow(),2);
           model.setValueAt(quantity, tbl_exp.getSelectedRow(),3);
           model.setValueAt(Total, tbl_exp.getSelectedRow(),4);
                
            }
          
          
            }//end of try
        catch(Exception e){ 
            JOptionPane.showMessageDialog(null, e.getMessage());
         }//end of catch
        
    }//GEN-LAST:event_btn_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Expenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Expenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Expenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Expenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Expenses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DELETE;
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel goBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner s_quantity;
    private javax.swing.JTable tbl_exp;
    private javax.swing.JTextField txt_ExpTotal;
    private javax.swing.JTextField txt_ItemName;
    private javax.swing.JTextField txt_Price;
    private javax.swing.JTextField txt_itemID;
    // End of variables declaration//GEN-END:variables

}
