/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RestarurantPages;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


public class FoodItem extends javax.swing.JFrame {
     Connection con=null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form FoodItem
     */
    public FoodItem() {
        initComponents();
         con = DBConnect.connect();
         Category();
          tbl_FoodItem.setAutoCreateRowSorter(true);// Alphabetical  order 
          FoodItem_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_itemID = new javax.swing.JTextField();
        txt_Price = new javax.swing.JTextField();
        txt_ItemName = new javax.swing.JTextField();
        txt_searchItemID = new javax.swing.JTextField();
        cmb_category = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_FoodItem = new javax.swing.JTable();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_searchItemID = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        MenuItem_foodcategory = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(248, 148, 6));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setPreferredSize(new java.awt.Dimension(990, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FOOD ITEMS");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_food_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(587, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 120));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel2.setText("Add Food Item");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Search Item ID :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Item ID :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Item Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Price :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Category :");

        txt_itemID.setEditable(false);
        txt_itemID.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txt_Price.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_Price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_PriceKeyPressed(evt);
            }
        });

        txt_ItemName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        txt_searchItemID.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_searchItemID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchItemIDKeyPressed(evt);
            }
        });

        cmb_category.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        cmb_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        tbl_FoodItem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl_FoodItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Item Name", "Price", "Category"
            }
        ));
        jScrollPane1.setViewportView(tbl_FoodItem);

        btn_add.setBackground(new java.awt.Color(248, 148, 6));
        btn_add.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_add.setText("ADD");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(248, 148, 6));
        btn_update.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(248, 148, 6));
        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_searchItemID.setBackground(new java.awt.Color(248, 148, 6));
        btn_searchItemID.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_searchItemID.setText("Search");
        btn_searchItemID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchItemIDActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(248, 148, 6));
        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_searchItemID, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_searchItemID)
                        .addGap(81, 81, 81))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_Price, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                            .addComponent(txt_itemID)
                                            .addComponent(txt_ItemName))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(cmb_category, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn_clear))
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1)
                        .addGap(28, 28, 28))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_add)
                .addGap(70, 70, 70)
                .addComponent(btn_update)
                .addGap(61, 61, 61)
                .addComponent(btn_delete)
                .addGap(168, 168, 168))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txt_searchItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_searchItemID)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_itemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmb_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(btn_clear))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_update)
                    .addComponent(btn_add)
                    .addComponent(btn_delete))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 990, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu4.setText("Open");

        MenuItem_foodcategory.setText("Food Category");
        MenuItem_foodcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_foodcategoryActionPerformed(evt);
            }
        });
        jMenu4.add(MenuItem_foodcategory);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        
         //ask the user is he/she want to add new item 
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to add this Item?","Add Item",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(x==0){
        try{
            //add the new item into the database
            String I ="INSERT INTO `add_fooditem`(`Item Name`, `Price`, `Category`) VALUES (?,?,?)"; 
            pst=con.prepareStatement(I);
            pst.setString(1, txt_ItemName.getText());
            pst.setString(2, txt_Price.getText());
            pst.setString(3, cmb_category.getSelectedItem().toString());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Item Added");
        }//end of try
        catch(Exception e){       
        }//end of catch
   }//end of if 
   
 FoodItem_table();//calling the method
        
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        //clear button
        txt_ItemName.setText("");
        txt_itemID.setText("");
        txt_Price.setText("");
        txt_searchItemID.setText("");
        cmb_category.setSelectedIndex(0);     
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        //ask the user if he/she want to update the item
         int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to update this item  ?","Update Item",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(x==0){
         try{
             //update all the vlaues that id is type in the search field
              String v1 = txt_itemID.getText();
              String v2 = txt_ItemName.getText();
              String v3 = txt_Price.getText();
              String v4 = cmb_category.getSelectedItem().toString();
              String U = "UPDATE `add_fooditem` SET  `Item ID`= '"+v1+"',`Category`='"+v4+"' ,`Item Name`='"+v2+"',`Price`='"+v3+"' WHERE `Item ID`= '"+v1+"'";
              pst = con.prepareStatement(U);
              pst.executeUpdate();
              JOptionPane.showMessageDialog(null, "Item Updated");  
              FoodItem_table();
              }//end of try
            catch(Exception e){ 
                 }//end of catch
            }//end of if
        
       
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        //ask the user if he/she want to delete  the item
         int z = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this Itme ?","Delete item",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(z==0){  
        try{
            //dlete the item that id is typed in the search field
           String D = "DELETE FROM `add_fooditem` WHERE `Item ID` =?";
           pst = con.prepareStatement(D);
           pst.setString(1, txt_searchItemID.getText());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Item Deleted");
        }//end of try
        catch(Exception e){
            }//end of catch
        }//end of if
    FoodItem_table();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_searchItemIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchItemIDActionPerformed
        // TODO add your handling code here:
            try{
                // displaying all thge values from databse to the filds where id is typed in the search field
                String s = "SELECT * FROM `add_fooditem` WHERE `Item ID`=? ";
                pst = con.prepareStatement(s);
                pst.setString(1,txt_searchItemID.getText());
                rs=pst.executeQuery();
            if(rs.next()){   
                String id =rs.getString("Item ID");
                txt_itemID.setText(id);

                String FC =rs.getString("Item Name");
                txt_ItemName.setText(FC);

                String FD =rs.getString("Price");
                txt_Price.setText(FD);
                
                String Category = rs.getString("Category");
                cmb_category.setSelectedItem(Category);  
            }//end of if 
        
        }//end of try
        catch(Exception e){   
        }//end of catch    
    }//GEN-LAST:event_btn_searchItemIDActionPerformed

    private void MenuItem_foodcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_foodcategoryActionPerformed
        // TODO add your handling code here:
        //send you back to food category
        this.toBack();
        FoodCategory FC= new FoodCategory();
        FC.setVisible(true);
        FC.toFront();
        this.dispose(); 
    }//GEN-LAST:event_MenuItem_foodcategoryActionPerformed

    private void txt_PriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PriceKeyPressed
        // TODO add your handling code here:
        String price = txt_Price.getText();
        int length = price.length();
        
        if(evt.getKeyChar()>= '0' && evt.getKeyChar()<='9' || evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
              txt_Price.setEditable(true);
            }//end of  if
            else{
                txt_Price.setEditable(false);
            }//end of  else
    }//GEN-LAST:event_txt_PriceKeyPressed

    private void txt_searchItemIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchItemIDKeyPressed
        // TODO add your handling code here:
               String search = txt_searchItemID.getText();
        int length = search.length();
        
        if(evt.getKeyChar()>= '0' && evt.getKeyChar()<='9' || evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
              txt_searchItemID.setEditable(true);
            }//end of  if
            else{
                txt_searchItemID.setEditable(false);
            }//end of  else
        
    }//GEN-LAST:event_txt_searchItemIDKeyPressed
   //method that call all the values from the Food Category column and displaying into the combobox
    private void Category(){
    try{
        String c = "Select `Food Category` FROM  `food category`";
        pst=con.prepareStatement(c);
        rs=pst.executeQuery();
        
        while(rs.next()){
        String categ = rs.getString("Food Category");
        cmb_category.addItem(categ);
        }//end of while 
    }//end of try
    catch(Exception e){
       }//end of catch
    }//end of method
    
    //displaying al the values from databse to jtable
    public void FoodItem_table(){
        try{
        String sql = "SELECT `Item ID`, `Item Name`, `Price`, `Category` FROM `add_fooditem` ";
        pst = con.prepareStatement(sql);
         rs=pst.executeQuery();
        tbl_FoodItem.setModel(DbUtils.resultSetToTableModel(rs));
        
        }//end of try
        catch(Exception e){
        }//end of catch
    }//end of method
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItem_foodcategory;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_searchItemID;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cmb_category;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_FoodItem;
    public static javax.swing.JTextField txt_ItemName;
    private javax.swing.JTextField txt_Price;
    private javax.swing.JTextField txt_itemID;
    private javax.swing.JTextField txt_searchItemID;
    // End of variables declaration//GEN-END:variables
}
